### ISSUE TITLE
DIN 8 (video socket) pins 6 and 7 are swapped

### ISSUE THREAD

**Issue by r1me** [KicadRetroArchive/kicad-retro-library#1]
Pin 6 and 7 are swapped in C64_Original_DIN-8_Circular.kicad_mod, would lead to expecting chrominance signal on NC pin.
Before:
![din8wrong](https://user-images.githubusercontent.com/13695767/136013599-c7fe5416-f86f-49d6-a0ac-134f73a08e07.png)
Fixed:
![din8corrected](https://user-images.githubusercontent.com/13695767/136013597-e45f94bf-5a20-4932-9e1b-6de31f261b8a.png)

**Comment by acisternino** [comment]
Thanks for the report.

I have fixed the issue and new releases of the library and the C64D project will come soon.
